[[inputs.mqtt_consumer]]
  servers = ["mqtt://broker.emqx.io:1883"]
  topics = ["tania/fakeplc/data"]
  qos = 0
  username = "admin"
  password = "admin"
  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "plc_measurements"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "machineId"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "line"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temperature"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "pressure"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "status"
      type = "string"

[[outputs.influxdb_v2]]
  urls = ["https://influxdb.tania.vm.service-ventury.de"]
  token = "AqSWjv9_OMw8FYnISXVTvF9m8U_k7wcExumgsMGb16T_P8rhcF8SnLiaQSTnVIUCNzNITQzE-D8Up7FdfEzjRQ=="
  organization = "Mahata_Ventury"
  bucket = "mqtt_data"